### ISSUE TITLE
yarpdev: ***ERROR*** could not find device <vicon>

### ISSUE THREAD

**Issue by kouroshD** [robotology/yarp-vicon-bridge#11]
following the instructions provided in README.md, I have tried to install `yap-vicon-bridge` in my laptop. After installation, by setting the value `<path to robotology>/robotology-superbuild/build/install`  for the variable `CMAKE_INSTALL_PREFIX`, It correctly installs the configuration file and he shared library in `robotology-superbuild/build/install/share/yarp/plugins/vicon_device.ini` and `robotology-superbuild/build/install/lib/yarp/yarp_vicon.so`.

However, When later I try the yarpserver, and `yarpdev --list | grep vicon` returns nothing, or `yarpdev --device vicon --hostname "192.168.10.2"` it does not work and give the following error:
```
[ERROR]Cannot find "vicon" plugin (not built in, and no .ini file found for it)
Check that YARP_DATA_DIRS leads to at least one directory with plugins/vicon.ini or share/yarp/plugins/vicon.ini in it
yarpdev: ***ERROR*** could not find device <vicon>
[ERROR]yarpdev: ***ERROR*** device not available.
[INFO]Suggestions:
[INFO]+ Do "yarpdev --list" to see list of supported devices.
[INFO]+ Or append "--verbose" option to get more information.
```
@Nicogene  @traversaro @Yeshasvitvs  @S-Dafarra  @GiulioRomualdi @lrapetti @prashanthr05

**Comment by Nicogene** [comment]
Thanks @kouroshD for reporting, it should be fixed now
