### ISSUE TITLE
Understand the problem with the frames transformation

### ISSUE THREAD

**Issue by kouroshD** [robotology/yarp-vicon-bridge#14]
When collecting the data, we noticed that we when after creating the segments, when we want to collect the data, the `transformserver` provides the information of the markers (i.e., positions) for the markers attached to a segment, but it does not expose the information of the frame attached to the segment. The output of the segment frame for an instance would be like: `(Vicon_ROOT "Subj_StEFI::Seg_StEFI" 33861.2320026340021286 0.0 0.0 0.0 0.0 0.5 0.0 0.0)` .

cc @aikolina  @prashanthr05  @Nicogene

**Comment by aikolina** [comment]
After running the `yarp-vicon-bridge` as described in the main README of the repository, I usually dump the Vicon data from the `/transformServer/transforms:o` using `yarpdatadumper`.

Ideally, we should get something like the following:

> 13426 273786.350415 **(Vicon_ROOT "Subj_StEFI::Seg_StEFI" 273786.342668224009685 -0.245219617586228622041 1.08339545121260849569 0.736312392598410969669 0.513008837964266439791 -0.458428544665524073665 0.580682140920149136853 0.435285484277611489645)** (Vicon_ROOT "Subj_StEFI::Marker_origin" 273786.342801032005809 -0.244223536643191546647 1.08377768961159093308 0.735670469794552195353 1.0 0.0 0.0 0.0) (Vicon_ROOT "Subj_StEFI::Marker_primaryAxis" 273786.342957575980108 -0.261229836554022654127 1.00233846847775009969 0.743021534518372162026 1.0 0.0 0.0 0.0) (Vicon_ROOT "Subj_StEFI::Marker_secondaryAxis" 273786.343087679997552 -0.355142190054025197465 1.10652054318853787507 0.74068175958540982684 1.0 0.0 0.0 0.0) (Vicon_ROOT "Subj_StEFI::Marker_bottomLeft" 273786.343236411979888 -0.229838418028291940898 1.06864798475669831035 0.637668301255225222768 1.0 0.0 0.0 0.0) (Vicon_ROOT "Subj_StEFI::Marker_topRight" 273786.343384544015862 -0.390982028333842268619 1.03068135353397605236 0.725229034468480193709 1.0 0.0 0.0 0.0) (Vicon_ROOT "Subj_StEFI::Marker_bottomFron" 273786.343535981024615 0.0 0.0 0.0 1.0 0.0 0.0 0.0)

However, during our last data collection, we got:

> 1985 28048.239205 **(Vicon_ROOT "Subj_StEFI::Seg_StEFI" 28048.2315720609985874 0.0 0.0 0.0 0.0 0.5 0.0 0.0)** (Vicon_ROOT "Subj_StEFI::Marker_origin" 28048.231987309998658 0.0414839350282885516163 0.0372712313936814088056 0.245283545560278148923 1.0 0.0 0.0 0.0) (Vicon_ROOT "Subj_StEFI::Marker_primaryAxis" 28048.2322529250013758 0.0350293359803204584768 -0.0443675338982194231163 0.243212400498661274195 1.0 0.0 0.0 0.0) (Vicon_ROOT "Subj_StEFI::Marker_secondaryAxis" 28048.2326907089991437 -0.0704520749957681102771 0.0479173101403580631308 0.245099201772005531597 1.0 0.0 0.0 0.0) (Vicon_ROOT "Subj_StEFI::Marker_bottomLeft" 28048.2330515729991021 0.0630727437963277681732 0.0387716656146335561517 0.144699014247940960232 1.0 0.0 0.0 0.0) (Vicon_ROOT "Subj_StEFI::Marker_topRight" 28048.2331912910012761 -0.0972514128744558642437 -0.0288573458533679001736 0.221089695409417946736 1.0 0.0 0.0 0.0) (Vicon_ROOT "Subj_StEFI::Marker_bottomFron" 28048.233321394000086 -0.0776617577890917898387 -0.0496725840057253426041 0.140965408103002454165 1.0 0.0 0.0 0.0)

So, the quaternion expressing the orientation of the segment was not correctly filled.

I remember that this issue already happened in the past, however, I don't remember how we actually solved it. :V

**Comment by aikolina** [comment]
**Side note:** the last time I managed to collect "good" data was _June 30th, 2020_ while @prashanthr05 noticed this misbehaviour from _July 20th, 2020_. The Vicon setup we have been using is the one in R1 kitchen in S. Quirico.

**Comment by Nicogene** [comment]
The `yarp-vicon-bridge` is a thin sw layer that uses the Vicon API for getting the tf and YARP for publishing them.
In a similar way of [`ros-vicon-bridge`](http://wiki.ros.org/vicon_bridge).

This issue should be or Vicon side(something has not been setup correctly) or YARP.

For checking that everything is fine Vicon side you can run their example executable(that essentially does the same things of `yarp-vicon-bridge` except for the yarp part).

It should be located in the SDK folder, it should be something like DataStreamCPP.exe

**Comment by aikolina** [comment]
I think it could be also interesting enabling the `test_frame` option.

https://github.com/robotology/yarp-vicon-bridge/blob/da8f6f9f5ff933af0a79180f8d524359dd96b262/src/YarpViconBridge.cpp#L109-L112

By running the `yarp-vicon-bridge` with this option, it should always send an identity matrix:

https://github.com/robotology/yarp-vicon-bridge/blob/da8f6f9f5ff933af0a79180f8d524359dd96b262/src/YarpViconBridge.cpp#L346-L354

However, I noticed that this parameter is actually missing from the constructor:

https://github.com/robotology/yarp-vicon-bridge/blob/da8f6f9f5ff933af0a79180f8d524359dd96b262/src/YarpViconBridge.cpp#L20-L44

@kouroshD So, we should make a local fix and try it out!

**Comment by aikolina** [comment]
I've just run the executable provided by the Vicon SDK (`ViconDataStreamSDK_CPPTest.exe`), and I've got the following output:

![ViconDataStreamSDK_CPPTest_01](https://user-images.githubusercontent.com/12125604/94019782-78263f80-fdb2-11ea-8c3d-d02f2839a92e.PNG)

So, also the official CPP test does not provide any **Global Rotation Matrix** which is actually the information used by the vicon-bridge:

https://github.com/robotology/yarp-vicon-bridge/blob/da8f6f9f5ff933af0a79180f8d524359dd96b262/src/YarpViconBridge.cpp#L405-L406

Therefose, the issue seems to be on the Vicon side (either Vicon Nexus or Vicon SDK).

**Comment by aikolina** [comment]
@prashanthr05 and I did also made another test and checked all the return values of the function `getGlobalSegmentRotationMatrix`.

The function returns the followings values:
|        |          |           |                             |
|--------|----------|-----------|-----------------------------|
| Output | Success  | Results   | **(0)** Result.Success, **(1)** Result.NotConnected, **(2)** Result.NoFrame, **(3)** Result.InvalidSubjectName, **(4)** Result.InvalidSegmentName      |
|        | Rotation | double[9] | The rotation of the segment |
|        | Occluded | boolean   | [[Ref 1]](http://andrewd.ces.clemson.edu/courses/cpsc412/manuals/Vicon%20DataStream%20SDK%20Manual.pdf) True if the segment was present at this frame. If False, then Rotation will be all 0. [[Ref 2]](https://docs.vicon.com/download/attachments/95684225/Vicon%20DataStream%20SDK%20Developer%27s%20Guide.pdf?version=1&modificationDate=1586347022000&api=v2) True if the segment was absent at this frame.                           |

In our case, we got `Result.NoFrame` and `Occluded = True`.

However, the meaning of those values is not clear. Especially for `Occluded`, we found two descriptions which go against each other. 😞

**Comment by aikolina** [comment]
It was, indeed, an issue related to Vicon Nexus. It was necessary to change the live processing parameters from **Label** to **Kinematic Fit** by clicking on _Local Vicon System_ in the _System Resources pane_ and then in the _Properties pane_ going to the _General_ section and selecting the required _Processing Output Level_.

![vicon_processingOutputLevel](https://user-images.githubusercontent.com/12125604/94570651-5aa01c80-026f-11eb-8247-1c28eb2075a0.PNG)
