### ISSUE TITLE
Trying to use yarp-vicon-bridge without using ROS and R1 setup

### ISSUE THREAD

**Issue by prashanthr05** [robotology/yarp-vicon-bridge#3]
With @GiulioRomualdi, we were trying to run this bridge to access VICON data through YARP.

We were running yarpserver without option --ros nor using any R1 specific software.  When we try to run the vicon device, we see that the device opens successfully but the data is not updated. 

When we try to list the transforms using `yarp rpc /transformSever/rpc` there are no transforms listed.

We would like to know if we are missing to launch something?

Thanks in advance.

**Comment by aerydna** [comment]
not so long ago i forked the yarp-vicon-bridge and some other devices modifying them in order to use an alternative transform stack with some of the problem resolved (no transform server, receiving the tf data using directly the native network api of the vicon wrapped in a yarp device). basically is the `newFrameInterface` branch of yarp-vicon-bridge using the alternative yarp transform stack in a stand-alone version (taken out from the yarp branch who's newFrameInterface is dependent on).
https://github.com/aerydna/yarp_addons.git

 the software is was well tested but sadly the CMake part is quite not finished (as i'm doing it in the spare tim). if you plan to work a lot with the vicon this will make your life better. you are interested i can fixup the build part and we can try integrating it in your workflow

**Comment by traversaro** [comment]
Just to understand, besides the improvements and innovations in @aerydna's new repo, the code in this repo is working or has some problems?

**Comment by prashanthr05** [comment]
@aerydna That's great. I will take a look. 

>  if you plan to work a lot with the Vicon this will make your life better.

As a general answer, I'd say yes. In the coming time, we would like to have ground truth for our control and estimation algorithms used for running walking experiments. 
Given that you have a hands-on experience on Vicon, by any chance would you also have a consolidated tutorial on using the Vicon Nexus software and how it needs to be configured to be used alongside with this yarp-vicon bridge?

**Comment by aerydna** [comment]
@traversaro i would not say the code on this particular repo but some code it depends on

**Comment by aerydna** [comment]
@prashanthr05 for configuring the vicon-bridge i think the doc on the repo is still a valid resource. on the Vicon Nexus software we run into and resolved-workaround some problem it has (one curious issue was that sometimes it stops sending data until you **save** (!!) the project) but there isn't any documentation on these issues. maybe we can arrange a heavy debugging session

**Comment by prashanthr05** [comment]
@aerydna first of all, I would like to learn how to actually use the Vicon setup to get data for our experiments. Still on level 1 (novice). I think the debugging for me comes after. ;D

The former already seems to be difficult given the fact that the Nexus software by itself is very unintuitive and going through a manual of 300 pages to understand its basic working is very expensive.

**Comment by aikolina** [comment]
I was looking for some instructions on how to use the `yarp-vicon-bridge` but I am pretty confused both by this issue and the main README.

- Are there any instructions on how to use the device without ROS and R1?
- Shall I use the code in the `master` branch or the one in `newFrameInterface`?

I am available for updating the documentation, as long as someone could explain to me how to use this device.

**Comment by Nicogene** [comment]
The instructions has been written time ago, for using it with R1 setup, but it can be used either without R1 and without ROS.

The ROS part was only for visualize the tf with rviz.

> I am available for updating the documentation, as long as someone could explain to me how to use this device

:tada: :tada:

**Comment by aikolina** [comment]
The instructions on how to use the `yarp-vicon-bridge` device without ROS and R1 will be available on the main README as soon as PR #9 is going to be merged.

**Comment by Nicogene** [comment]
#9 should have removed all doubts about the usage of this device, closing.
